MyQuizlet.Web/Controllers/CardsController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyQuizlet.Application.CQRSFeatures.Card.Commands.CreateCard;
using MyQuizlet.Application.CQRSFeatures.Card.Commands.DeleteCard;
using MyQuizlet.Application.CQRSFeatures.Card.Commands.UpdateCard;
using MyQuizlet.Application.CQRSFeatures.Card.Queries.GetAllCards;
using MyQuizlet.Application.CQRSFeatures.Card.Queries.GetCardById;
using MyQuizlet.Application.CQRSFeatures.Card.Queries.GetSortedCards;
using MyQuizlet.Application.CQRSFeatures.Deck.Queries.GetDeckNames;
using MyQuizlet.Application.Enums;

namespace MyQuizlet.Web.Controllers
{
    [Controller]
    [Route("[controller]")]
    public class CardsController : Controller
    {
        private readonly IMediator _mediator;

        public CardsController(IMediator mediatR)
        {
            _mediator = mediatR;
        }

        [HttpGet("all")]
        public async Task<IActionResult> GetAllCards(string? searchBy, string? searchString, string? sortBy, Sorting? sortOrder)
        {
            ViewBag.SearchByProps = new List<SelectListItem>
            {
                new SelectListItem { Text = "Term", Value = nameof(GetAllCardsDto.Term) },
                new SelectListItem { Text = "Definition", Value = nameof(GetAllCardsDto.Definition) },
                new SelectListItem { Text = "EnglishLevel", Value = nameof(GetAllCardsDto.EnglishLevel) },
            };

            var cards = await _mediator.Send(new GetAllCardsQuery(searchBy, searchString));

            cards = await _mediator.Send(new GetSortedCardsQuery(cards, sortBy, sortOrder));

            ViewBag.CurrentSortOrder = sortOrder;
            ViewBag.CurrentSortBy = sortBy;
            ViewBag.CurrentSearchBy = searchBy;
            ViewBag.CurrentSearchString = searchString;

            return View(cards);
        }

        [HttpGet("getbyid/{id:guid}")]
        public async Task<IActionResult> GetCardById(Guid id)
        {
            var card = await _mediator.Send(new GetCardByIdQuery(id));

            return View(card);
        }

        [HttpGet("create")]
        public async Task<IActionResult> CreateCard()
        {
            var decks = await _mediator.Send(new GetDeckNamesQuery());
            ViewBag.Decks = new SelectList(decks, "Id", "DeckName");
            return View();
        }

        [HttpPost("create")]
        public async Task<IActionResult> CreateCard(CreateCardCommand card)
        {
            if (!ModelState.IsValid)
            {
                var decks = await _mediator.Send(new GetDeckNamesQuery());
                ViewBag.Decks = new SelectList(decks, "Id", "DeckName");

                return View();
            }

            var result = await _mediator.Send(card);

            if (result == false)
                return BadRequest(ModelState);

            return RedirectToAction("GetAllCards");
        }

        [HttpGet("update/{id:guid}")]
        public async Task<IActionResult> UpdateCard(Guid id)
        {
            var card = await _mediator.Send(new GetCardByIdQuery(id));
            ViewBag.Card = card;

            var decks = await _mediator.Send(new GetDeckNamesQuery());
            ViewBag.Decks = new SelectList(decks, "Id", "DeckName");

            return View();
        }

        [HttpPost("update/{id:guid}")]
        public async Task<IActionResult> UpdateCard(Guid id, UpdateCardCommand card)
        {
            //TODO попробовать добавить [FromBody], чтобы Id не добавлялось в URL
            if (!ModelState.IsValid)
                return View();

            var result = await _mediator.Send(card);

            if (result == false)
            {
                ViewBag.Card = card;

                var decks = await _mediator.Send(new GetDeckNamesQuery());
                ViewBag.Decks = new SelectList(decks, "Id", "DeckName");
                return View();
            }

            return RedirectToAction("GetAllCards");
        }

        [HttpGet("delete/{id:guid}")]
        public async Task<IActionResult> DeleteCard(Guid id)
        {
            var card = await _mediator.Send(new GetCardByIdQuery(id));

            return View(card);
        }

        [ActionName("DeleteCard")]
        [HttpPost("delete/{id:guid}")]
        public async Task<IActionResult> DeleteCardConfirmed(Guid id)
        {
            var result = await _mediator.Send(new DeleteCardCommand(id));

            if (result == false)
                return View();

            return RedirectToAction("GetAllCards");
        }
    }
}

MyQuizlet.Web/Controllers/DecksController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using MyQuizlet.Application.CQRSFeatures.Card.Queries.GetAllCards;
using MyQuizlet.Application.CQRSFeatures.Card.Queries.GetSortedCards;
using MyQuizlet.Application.CQRSFeatures.Deck.Commands.CreateDeck;
using MyQuizlet.Application.CQRSFeatures.Deck.Commands.DeleteDeck;
using MyQuizlet.Application.CQRSFeatures.Deck.Commands.UpdateDeck;
using MyQuizlet.Application.CQRSFeatures.Deck.Queries.GetAllDecks;
using MyQuizlet.Application.CQRSFeatures.Deck.Queries.GetDeckById;
using MyQuizlet.Application.CQRSFeatures.Deck.Queries.GetDeckCardsByDeckId;
using MyQuizlet.Application.CQRSFeatures.Deck.Queries.GetSortedDecks;
using MyQuizlet.Application.Enums;
using MyQuizlet.Domain.Entities;
using System.Globalization;

namespace MyQuizlet.Web.Controllers
{
    [Controller]
    [Route("[controller]")]
    public class DecksController : Controller
    {
        private readonly IMediator _mediator;

        public DecksController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet("all")]
        public async Task<IActionResult> GetAllDecks(string? searchBy, string? searchString, string? sortBy, Sorting? sortOrder)
        {
            ViewBag.SearchByProps = new List<SelectListItem>
            {
                new SelectListItem { Text = "Deck Name", Value = nameof(GetAllDecksDto.DeckName) },
                new SelectListItem { Text = "Description", Value = nameof(GetAllDecksDto.Description) },
            };

            var decks = await _mediator.Send(new GetAllDecksQuery(searchBy, searchString));

            decks = await _mediator.Send(new GetSortedDecksQuery(decks, sortBy, sortOrder));

            ViewBag.CurrentSortOrder = sortOrder;
            ViewBag.CurrentSortBy = sortBy;
            ViewBag.CurrentSearchBy = searchBy;
            ViewBag.CurrentSearchString = searchString;

            return View(decks);
        }

        [HttpGet("getbyid/{id:guid}")]
        public async Task<IActionResult> GetDeckById(Guid id)
        {
            var deck = await _mediator.Send(new GetDeckByIdQuery(id));

            return View(deck);
        }

        [HttpGet("getcardsbyid/{id:guid}")]
        public async Task<IActionResult> GetDeckCards(Guid id, string? searchBy, string? searchString, string? sortBy, Sorting? sortOrder)
        {
            ViewBag.SearchByProps = new List<SelectListItem>
            {
                new SelectListItem { Text = "Term", Value = nameof(GetAllCardsDto.Term) },
                new SelectListItem { Text = "Definition", Value = nameof(GetAllCardsDto.Definition) },
                new SelectListItem { Text = "EnglishLevel", Value = nameof(GetAllCardsDto.EnglishLevel) },
            };
            var deckCards = await _mediator.Send(new GetDeckCardsByDeckIdQuery(id, searchBy, searchString));
            
            deckCards.Cards = await _mediator.Send(new GetSortedCardsQuery(deckCards.Cards, sortBy, sortOrder));

            ViewBag.CurrentSortOrder = sortOrder;
            ViewBag.CurrentSortBy = sortBy;
            ViewBag.CurrentSearchBy = searchBy;
            ViewBag.CurrentSearchString = searchString;

            return View(deckCards);
        }

        [HttpGet("create")]
        public IActionResult CreateDeck()
        {
            return View();
        }

        [HttpPost("create")]
        public async Task<IActionResult> CreateDeck(CreateDeckCommand deck)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _mediator.Send(deck);

            if (result == false)
                return BadRequest();

            return RedirectToAction("GetAllDecks");
        }

        [HttpGet("update/{id:guid}")]
        public async Task<IActionResult> UpdateDeck(Guid id)
        {
            var deck = await _mediator.Send(new GetDeckByIdQuery(id));
            ViewBag.Deck = deck;

            return View();
        }

        [HttpPost("update/{id:guid}")]
        public async Task<IActionResult> UpdateDeck(Guid id, UpdateDeckCommand deck)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _mediator.Send(deck);

            if (result == false)
            {
                ViewBag.Deck = deck;
                return View();
            }
            return RedirectToAction("GetAllDecks");
        }

        [HttpGet("delete/{id:guid}")]
        public async Task<IActionResult> DeleteDeck(Guid id)
        {
            var deck = await _mediator.Send(new GetDeckByIdQuery(id));
            return View(deck);
        }

        [ActionName("DeleteDeck")]
        [HttpPost("delete/{id:guid}")]
        public async Task<IActionResult> DeleteDeckConfirmed(Guid id)
        {
            var result = await _mediator.Send(new DeleteDeckCommand(id));

            if (result == false)
            {
                var deck = await _mediator.Send(new GetDeckByIdQuery(id));
                return View(deck);
            }

            return RedirectToAction("GetAllDecks");
        }
    }
}

MyQuizlet.Web/Views/Decks/CreateDeck.cshtml
@using MyQuizlet.Application.CQRSFeatures.Deck.Commands.CreateDeck;
@using System.Security.Claims;
@model CreateDeckCommand;

@{
    ViewBag.Title = "Create deck";
}

<h1>Create deck</h1>

<form asp-controller="Decks" asp-action="CreateDeck" method="post">
    <div class="row justify-content-center">
        <a class="btn btn-outline-primary" asp-controller="Decks" asp-action="GetAllDecks">Back to Decks List</a>
        
        <input type="hidden" asp-for="ApplicationUserId" value="@User.FindFirstValue(ClaimTypes.NameIdentifier)" />
        
        <div>
            <label asp-for="DeckName" class="form-label">Deck Name:</label>
            <input class="form-control" asp-for="DeckName" placeholder="Enter" />
            <span asp-validation-for="DeckName" class="text-danger"></span>
        </div>

        <div>
            <label asp-for="Description">Description:</label>
            <input class="form-control" asp-for="Description" placeholder="Enter" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <h5>Are you sure to create this deck?</h5>
        <button class="btn btn-success">Create</button>
    </div>
</form>

MyQuizlet.Web/Views/Decks/DeleteDeck.cshtml
@using MyQuizlet.Application.CQRSFeatures.Deck.Queries.GetDeckById;
@model GetDeckByIdDto;

@{
    ViewBag.Title = "Delete deck";
}

<h1>Delete deck</h1>

<form asp-controller="Decks" asp-action="DeleteDeck" method="post">
    <div class="row justify-content-center">
        <a asp-controller="Decks" asp-action="GetAllDecks" class="btn btn-outline-primary">Back to Decks List</a>
        
        <input type="hidden" asp-for="Id" disabled />
        
        <div>
            <label asp-for="DeckName" class="form-label">Deck Name:</label>
            <input asp-for="DeckName" class="form-control" disabled />
        </div>

        <div>
            <label asp-for="Description">Description:</label>
            <input asp-for="Description" class="form-control" disabled />
        </div>

        <h5>Are you sure to delete this deck?</h5>
        <button class="btn btn-success">Delete</button>
    </div>
</form>

MyQuizlet.Web/Views/Decks/GetAllDecks.cshtml
@using MyQuizlet.Application.CQRSFeatures.Deck.Queries.GetAllDecks;
@model IEnumerable<GetAllDecksDto>;

@{
    ViewBag.Title = "Get decks";
}

<h1>All decks:</h1>

<a class="btn btn-primary" asp-controller="Decks" asp-action="CreateDeck">Create new deck</a>

<form asp-controller="Decks" asp-action="GetAllDecks" method="get">
    <div class="input-group">
        <input class="form-control" name="searchString" value="@ViewBag.CurrentSearchString" placeholder="Search string" />
        <select class="custom-select" name="searchBy">
            @foreach (var value in ViewBag.SearchByProps)
            {
                <option value="@value.Value" selected="@(value.Value == ViewBag.CurrentSearchBy)">@value.Text</option>
            }
        </select>
        <div class="input-group-append">
            <button class="btn btn-primary">Search</button>
            <a class="btn btn-danger" asp-controller="Decks" asp-action="GetAllDecks">Clear</a>
        </div>
    </div>
</form>

@{
    await Html.RenderPartialAsync("_DecksPartialView", Model);
}

MyQuizlet.Web/Views/Decks/GetDeckById.cshtml
@using MyQuizlet.Application.CQRSFeatures.Deck.Queries.GetDeckById;
@model GetDeckByIdDto;

@{
    ViewBag.Title = "Get deck";
}

<p>get deck by id</p>

MyQuizlet.Web/Views/Decks/GetDeckCards.cshtml
@using MyQuizlet.Application.CQRSFeatures.Deck.Queries.GetDeckCardsByDeckId;
@model GetDeckCardsByDeckIdDto;

@{
    ViewBag.Title = "Get deck cards";
}

<h1>All deck cards:</h1>

@*TODO autoAdd deckId when create Card*@@*asp-route-deckId="@Model.Id"*@
<a class="btn btn-primary" asp-controller="Cards" asp-action="CreateCard">Add new card</a>

<form asp-controller="Decks" asp-action="GetDeckCards" method="get">
    <div class="input-group">
        <input class="form-control" name="searchString" value="@ViewBag.CurrentSearchString" placeholder="Search string" />
        <select class="custom-select" name="searchBy">
            @foreach (var value in ViewBag.SearchByProps)
            {
                <option value="@value.Value" selected="@(value.Value == ViewBag.CurrentSearchBy)">@value.Text</option>
            }
        </select>
        <div class="input-group-append">
            <button class="btn btn-primary">Search</button>
            <a class="btn btn-danger" asp-controller="Decks" asp-action="GetDeckCards">Clear</a>
        </div>
    </div>
</form>

@{
    await Html.RenderPartialAsync("_DeckCardsPartialView", Model);
}

MyQuizlet.Web/Views/Decks/UpdateDeck.cshtml
@using MyQuizlet.Application.CQRSFeatures.Deck.Commands.UpdateDeck;
@model UpdateDeckCommand;

@{
    ViewBag.Title = "Update deck";
}

<h1>Update deck</h1>

<form asp-controller="Decks" asp-action="UpdateDeck" method="post">
    <div class="row justify-content-center">
        <a class="btn btn-outline-primary"  asp-controller="Decks" asp-action="GetAllDecks">Back to Decks List</a>

        <input type="hidden" asp-for="Id" value="@ViewBag.Deck.Id" />

        <div>
            <label asp-for="DeckName" class="form-label">Deck Name:</label>
            <input asp-for="DeckName" value="@ViewBag.Deck.DeckName" class="form-control" placeholder="Enter" />
            <span asp-validation-for="DeckName" class="text-danger"></span>
        </div>

        <div>
            <label asp-for="Description">Description:</label>
            <input asp-for="Description" value="@ViewBag.Deck.Description" class="form-control" placeholder="Enter" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <h5>Are you sure to update this deck?</h5>
        <button class="btn btn-success">Update</button>
    </div>
</form>

MyQuizlet.Web/Views/Decks/_DeckCardsPartialView.cshtml
@using MyQuizlet.Application.CQRSFeatures.Card.Queries.GetAllCards;
@using MyQuizlet.Application.CQRSFeatures.Card.Queries.GetCardById;
@using MyQuizlet.Application.CQRSFeatures.Deck.Queries.GetDeckCardsByDeckId;
@using MyQuizlet.Application.Enums;
@model GetDeckCardsByDeckIdDto;

@{
    var currentSearchBy = ViewBag.CurrentSearchBy;
    var currentSearchString = ViewBag.CurrentSearchString;
    var currentSortBy = ViewBag.CurrentSortBy;
    var nextSortOrder = ViewBag.CurrentSortOrder == Sorting.ASC ? Sorting.DESC : Sorting.ASC;
}

<table class="table table-bordered table-hover table-sm">
    <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>
                <a 
                    asp-route-searchBy="@currentSearchBy" 
                    asp-route-searchString="@currentSearchString" 
                    asp-route-sortBy="@nameof(GetAllCardsDto.Term)" 
                    asp-route-sortOrder="@nextSortOrder" 
                    asp-controller="Decks" 
                    asp-action="GetDeckCards"
                >@nameof(GetAllCardsDto.Term)
                @if (currentSortBy == nameof(GetAllCardsDto.Term))
                {
                    if(nextSortOrder == Sorting.DESC)
                    {
                        <i class="bi bi-sort-alpha-up"></i>
                    }
                    else if (nextSortOrder == Sorting.ASC)
                    {
                        <i class="bi bi-sort-alpha-up-alt"></i>
                    }
                }
                </a>
            </th>
            <th>
                <a 
                    asp-route-searchBy="@currentSearchBy" 
                    asp-route-searchString="@currentSearchString" 
                    asp-route-sortBy="@nameof(GetAllCardsDto.Definition)" 
                    asp-route-sortOrder="@nextSortOrder" 
                    asp-controller="Decks" 
                    asp-action="GetDeckCards"
                >@nameof(GetAllCardsDto.Definition)
                @if (currentSortBy == nameof(GetAllCardsDto.Definition))
                {
                    if(nextSortOrder == Sorting.DESC)
                    {
                        <i class="bi bi-sort-alpha-up"></i>
                    }
                    else if (nextSortOrder == Sorting.ASC)
                    {
                        <i class="bi bi-sort-alpha-up-alt"></i>
                    }
                }
                </a>
            </th>
            <th>
                <a 
                    asp-route-searchBy="@currentSearchBy" 
                    asp-route-searchString="@currentSearchString" 
                    asp-route-sortBy="@nameof(GetAllCardsDto.EnglishLevel)" 
                    asp-route-sortOrder="@nextSortOrder" 
                    asp-controller="Decks" 
                    asp-action="GetDeckCards"
                >@nameof(GetAllCardsDto.EnglishLevel)
                @if (currentSortBy == nameof(GetAllCardsDto.EnglishLevel))
                {
                    if(nextSortOrder == Sorting.DESC)
                    {
                        <i class="bi bi-sort-alpha-up"></i>
                    }
                    else if (nextSortOrder == Sorting.ASC)
                    {
                        <i class="bi bi-sort-alpha-up-alt"></i>
                    }
                }
                </a>
            </th>
            <th>Options:</th>
        </tr>
    </thead>
    <tbody>
        @{
            int i = 1;
            foreach(var card in Model.Cards)
            {
                <tr>
                    <th>@(i++)</th>
                    <td>@card.Term</td>
                    <td>@card.Definition</td>
                    <td>@card.EnglishLevel</td>
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-warning" asp-controller="Cards" asp-action="UpdateCard" asp-route-id="@card.Id">Update</a>
                            <a class="btn btn-danger" asp-controller="Cards" asp-action="DeleteCard" asp-route-id="@card.Id">Delete</a>
                        </div>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

MyQuizlet.Web/Views/Decks/_DecksPartialView.cshtml
@using MyQuizlet.Application.CQRSFeatures.Deck.Queries.GetAllDecks;
@using MyQuizlet.Application.Enums;
@model IEnumerable<GetAllDecksDto>;

@{
    var currentSearchBy = ViewBag.CurrentSearchBy;
    var currentSearchString = ViewBag.CurrentSearchString;
    var currentSortBy = ViewBag.CurrentSortBy;
    var nextSortOrder = ViewBag.CurrentSortOrder == Sorting.ASC ? Sorting.DESC : Sorting.ASC;
}

<table class="table table-bordered table-hover table-sm">
    <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>
                <a 
                    asp-route-searchBy="@currentSearchBy" 
                    asp-route-searchString="@currentSearchString" 
                    asp-route-sortBy="@nameof(GetAllDecksDto.DeckName)" 
                    asp-route-sortOrder="@nextSortOrder" 
                    asp-controller="Decks" 
                    asp-action="GetAllDecks"
                >@nameof(GetAllDecksDto.DeckName)
                @if (currentSortBy == nameof(GetAllDecksDto.DeckName))
                {
                    if(nextSortOrder == Sorting.DESC)
                    {
                        <i class="bi bi-sort-alpha-up"></i>
                    }
                    else if (nextSortOrder == Sorting.ASC)
                    {
                        <i class="bi bi-sort-alpha-up-alt"></i>
                    }
                }
                </a>
            </th>
            <th>
                <a 
                    asp-route-searchBy="@currentSearchBy" 
                    asp-route-searchString="@currentSearchString" 
                    asp-route-sortBy="@nameof(GetAllDecksDto.Description)" 
                    asp-route-sortOrder="@nextSortOrder" 
                    asp-controller="Decks" 
                    asp-action="GetAllDecks"
                >@nameof(GetAllDecksDto.Description)
                @if (currentSortBy == nameof(GetAllDecksDto.Description))
                {
                    if(nextSortOrder == Sorting.DESC)
                    {
                        <i class="bi bi-sort-alpha-up"></i>
                    }
                    else if (nextSortOrder == Sorting.ASC)
                    {
                        <i class="bi bi-sort-alpha-up-alt"></i>
                    }
                }
                </a>
            </th>
            <th>Options:</th>
        </tr>
    </thead>
    <tbody>
        @{
            int i = 1;
            foreach(var deck in Model)
            {
                <tr>
                    <th>@(i++)</th>
                    <td>@deck.DeckName</td>
                    <td>@deck.Description</td>
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-info" asp-controller="Decks" asp-action="GetDeckCards" asp-route-id="@deck.Id">Cards</a>
                            <a class="btn btn-warning" asp-controller="Decks" asp-action="UpdateDeck" asp-route-id="@deck.Id">Update</a>
                            <a class="btn btn-danger" asp-controller="Decks" asp-action="DeleteDeck" asp-route-id="@deck.Id">Delete</a>
                        </div>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>