MyQuizlet.Web/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyQuizlet.Application.Enums;

namespace MyQuizlet.Web.Controllers
{
    [Controller]
    [Authorize(Roles = nameof(UserRoles.Admin))]
    public class AdminController : Controller
    {
        [Route("/adminpanel")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

MyQuizlet.Web/Controllers/IdentityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyQuizlet.Application.Contracts.Services;
using MyQuizlet.Application.DTO;

namespace MyQuizlet.Web.Controllers
{
    [Controller]
    [Route("[controller]")]
    [AllowAnonymous]
    public class IdentityController : Controller
    {
        private readonly IIdentityService _identityService;
        public IdentityController(IIdentityService identityService)
        {
            _identityService = identityService;
        }

        [HttpGet("[action]")]
        public IActionResult SignUp()
        {
            var model = new SignUpDto();
            return View(model);
        }

        [HttpPost("[action]")]
        public async Task<IActionResult> SignUp(SignUpDto model)
        {
            if (ModelState.IsValid)
            {
                var result = await _identityService.SignUpAsync(model);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("SignUp", error.Description);
                    }
                }
            }

            return View(model);
        }

        [HttpGet("[action]")]
        public IActionResult SignIn()
        {
            var model = new SignInDto();
            return View(model);
        }

        [HttpPost("[action]")]
        public async Task<IActionResult> SignIn(SignInDto model, string? ReturnUrl)
        {
            if (ModelState.IsValid)
            {
                var result = await _identityService.SignInAsync(model);
                if (result.Succeeded)
                {
                    if (!string.IsNullOrEmpty(ReturnUrl) && Url.IsLocalUrl(ReturnUrl))
                    {
                        return LocalRedirect(ReturnUrl);
                    }
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("SignIn", "Invalid email or password");
                }
            }

            return View(model);
        }

        public async Task<IActionResult> SignOut()
        {
            await _identityService.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet("[action]")]
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

MyQuizlet.Web/Views/Shared/_Layout.cshtml
@using MyQuizlet.Application.Enums;
<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    </head>
    <body>
        <div class="container">
            <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-primary">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">MyQuizlet</a>
                <div class="container-fluid">
                    <ul class="navbar-nav">
                        <a class="nav-item nav-link" asp-controller="Home" asp-action="GameManager">Play Game</a>
                        <a class="nav-item nav-link" asp-controller="Home" asp-action="CardsManager">Cards Manager</a>
                    </ul>
                    <ul class="navbar-nav navbar-right">
                        @if(User.Identity.IsAuthenticated){
                            if (User.IsInRole(nameof(UserRoles.Admin))){
                                <a class="nav-item nav-link" asp-controller="Admin" asp-action="Index">Admin Panel</a>
                            }
                            <a class="nav-item nav-link" asp-controller="Profile" asp-action="Settings">@User.Identity?.Name (Settings)</a>
                            <a class="nav-item nav-link" asp-controller="Identity" asp-action="SignOut">Sign Out</a>
                        }
                        else
                        {
                            <a class="nav-item nav-link" asp-controller="Identity" asp-action="SignIn">Sign In</a>
                        }                        
                    </ul>
                </div>
            </nav>

            <div>
                @RenderBody()
            </div>

            <div>
                @RenderSection("footer_section", false)
            </div>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

    </body>
</html>